import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>Data</code>
          </p>
          <div>
            <a
              href="https://archie-sandbox.cloudbuddies.online/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/archie_logo.png"
                alt="Archie Logo"
                className={styles.vercelLogo}
                width={60}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/archie.svg"
            alt="Archie Image"
            width={480}
            height={120}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="createTableDinamic"
            className={styles.card}
            // target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Create Table <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Create a table at DynamoDB.
            </p>
          </a>

          <a
            href="adddata"
            className={styles.card}
            // target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Add Data <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Add Data to DynamoDB&nbsp;table!
            </p>
          </a>

          <a
            href="viewdata"
            className={styles.card}
            // target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              View Data <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              View Data from a DynamoDB&nbsp;table.
            </p>
          </a>

          <a
            href="https://www.cloudbuddies.io/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              About Us<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Learn how Archie speeds up deployment
              in your&nbsp;company.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
